# 1. The Cloud Database URL (Notice the port 4000 and the security tag at the end)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/library_db?sslMode=VERIFY_IDENTITY

# 2. Your Cloud Username & Password
spring.datasource.username=4WwZLXYc6DM6Cne.root
spring.datasource.password=EGhTUbylDurBxq7E

# 3. Hibernate / JPA Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true